# Generated by Django 5.2 on 2025-05-31 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_dane', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('tipo_documento_codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_doc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadAdministradora',
            fields=[
                ('codigo_eapb', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id_etnia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadAtencion',
            fields=[
                ('id_modalidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadAtencion',
            fields=[
                ('id_prioridad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('id_via', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoCIE10',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('codigo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.diagnosticocie10')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id_ocupacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.ocupacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_doc', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('hora_nacimiento', models.CharField(max_length=20)),
                ('Municipio', models.CharField(max_length=15)),
                ('ciudad_residencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.ciudad')),
                ('codigo_eapb', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.entidadadministradora')),
                ('id_etnia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.etnia')),
                ('id_ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.ocupacion')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.documentoidentidad')),
            ],
        ),
        migrations.CreateModel(
            name='PresuncionDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_opone', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField()),
                ('motivo_atencion', models.TextField()),
                ('entorno', models.CharField(max_length=20)),
                ('fecha_hora_triage', models.CharField(max_length=20)),
                ('clasificacion_triage', models.CharField(max_length=20)),
                ('diagnostico_cie10', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.diagnosticocie10')),
                ('codigo_eapb', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.entidadadministradora')),
                ('id_modalidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.modalidadatencion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.paciente')),
                ('id_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.prioridadatencion')),
                ('id_via', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.viaingreso')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntadAnticipada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_url', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
                ('se_opone', models.CharField(blank=True, max_length=15, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.discapacidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'discapacidad')},
            },
        ),
        migrations.CreateModel(
            name='NacionalidadPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.paciente')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinicaApp.pais')),
            ],
            options={
                'unique_together': {('paciente', 'pais')},
            },
        ),
    ]
